/**
 * Optional file, can (should?) be autogenerated.
 */
let shareType = 'list';
let shareVendor = 'comms';
let shareName = 'unusual-list';

/**
 * Async load item template.
 * Register Vue component - hub-$type-$vendor-$name
 */
Vue.component(['hub-', shareType, '-', shareVendor, '-', shareName].join(), () => import('./' + shareName + ".vue"));